datasource-url: jdbc:h2:mem:db/beer
datasource-username: sa
datasource-password: sa

azure:
  keyvault:
    enabled: false

spring:
  flyway:
    enabled: true
  devtools:
    add-properties: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: true
