spring:
  datasource:
    url: jdbc:h2:mem:db/postgres
    username: sa
    password: sa
  flyway:
    enabled: true
    user: sa
    password: sa
    url: jdbc:h2:mem:db/postgres
    baseline-on-migrate: true
    locations: classpath:db
  devtools:
    add-properties: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
