spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  flyway:
    enabled: true
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    baseline-on-migrate: true
    locations: classpath:db
  devtools:
    add-properties: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true