# Fetch datasource values from Azure Key Vault
# azure.keyvault.{uri, client-id, client-key, tenant-id} should be provided at runtime
azure:
  keyvault:
    enabled: true
    secret-keys: datasource-url,datasource-username,datasource-password

spring:
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
  flyway:
    enabled: true
    url: ${datasource-url}
    user: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

