spring:
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
  flyway:
    enabled: true
    url: ${datasource-url}
    user: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

